export const ROLES = {
  ADMIN: 'ADMIN',
  TRAINER: 'TRAINER',
  HR: 'HR',
};

export const LEAVE_TYPES = {
  SICK: 'SICK',
  CASUAL: 'CASUAL',
  PAID: 'PAID',
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const NOTIFICATION_TYPES = {
  LEAVE_REQUEST: 'LEAVE_REQUEST',
  LEAVE_APPROVAL: 'LEAVE_APPROVAL',
  LEAVE_REJECTION: 'LEAVE_REJECTION',
  CLOCK_IN: 'CLOCK_IN',
  PASSWORD_RESET: 'PASSWORD_RESET',
  WELCOME: 'WELCOME',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE',
};

export const ATTENDANCE_STATUS = {
  CLOCKED_IN: 'CLOCKED_IN',
  CLOCKED_OUT: 'CLOCKED_OUT',
  INCOMPLETE: 'INCOMPLETE',
};

export const DEFAULT_LEAVE_BALANCE = {
  SICK: 10,
  CASUAL: 12,
  PAID: 20,
};

export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBER: true,
  REQUIRE_SPECIAL: true,
};